### PR TITLE
docsonnet go bin: Switch from pkger to embed

### PR DESCRIPTION
**Pull request by yorinasub17**
Fixes https://github.com/jsonnet-libs/docsonnet/issues/35

This updates the static file embedding logic to use the builtin [embed](https://pkg.go.dev/embed) instead of `pkger`, which has the advantage of dynamically embedding without code generation. This means that there is no need to maintain a separate `pkged.go` file every time `doc-util` or `load.libsonnet` is updated, as the latest version is always embedded even when installing `docsonnet` with `go install`.

Side note: I am aware from reading the issue that the fate of the go binary is in the air. Personally, I like the `docsonnet` go binary as it makes for a very quick installation process and keeps the source jsonnet libraries "clean" by reducing the number of entrypoints. Regardless, thought it made sense to update it for others who run into issues trying to use it.

### CODE REVIEW

**Review by Duologic — APPROVED** [review]
I can see how this improves the situation, I can recall using it in another project and it worked quite well.

**Comment by Duologic** [comment]
Hmm, I see the docker pipeline fail, I assume the credentials used were from @sh0rez and he changed them now.

**Comment by Duologic** [comment]
Now that we've switched to goreleaser, mind doing a rebase of this PR?

**Comment by yorinasub17** [comment]
Closing as superseded by #54

**Pull request closed without merging**
